#ifndef MAIN_H
#define MAIN_H
/**
 * @file main.h
 * @brief Header file for main.c
 */
/**
 * STD headers
 */
#include <fcntl.h>
#include <limits.h>
#include <pwd.h>
#include <signal.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
#include <dirent.h>
#include <libgen.h>
/**
 * Lib or deps headers
 */
#include <cjson/cJSON.h>

/**
 * Same folders here, with ""
 */

#include <stdbool.h>

/**
 * @brief Prints the shell prompt with user, hostname, and current working directory.
 *
 * This function retrieves the current user's name, hostname, and current working directory,
 * then prints them in a formatted prompt with colors. The colors are defined by the constants
 * USER_COLOR and PWD_COLOR, and the prompt is reset to the default color after printing.
 *
 * The format of the prompt is: (usr_clr)(username)@(hostname):(pwd_clr)(cwd)(reset_clr)$
 *
 * @note This function uses ANSI escape codes for coloring the prompt.
 *
 * @note The function exits with status 1 if it fails to get the current working directory.
 *
 * @note The function assumes that USER_COLOR and PWD_COLOR are defined elsewhere in the code.
 */
void print_prompt();

/**
 * @brief Executes a given command string.
 *
 * This function parses and executes a command string. It supports commands with
 * input/output redirection, background execution, and piped commands.
 *
 * @param command The command string to execute.
 *
 * The function handles the following built-in commands:
 * - cd: Change directory.
 * - clr: Clear the screen.
 * - echo: Display a line of text.
 * - quit: Exit the shell.
 * - fg: Bring a background job to the foreground.
 * - start_monitor: Start the hardware monitor.
 * - stop_monitor: Stop the hardware monitor.
 * - status_monitor: Display the status of the monitor.
 * - update_interval: Update the monitoring interval.
 * - add_metric: Add a metric to monitor.
 * - remove_metric: Remove a metric from monitoring.
 * - show_config: Show the current configuration.
 *
 * For other commands, it executes them as external commands.
 *
 * If the command contains pipes ('|'), it splits the command into individual
 * commands and executes them with piping.
 */
void execute_command(char* command);

/**
 * @brief Adds a child process ID to the list of child PIDs.
 *
 * This function stores the given child process ID (pid) in the global array
 * `child_pids` if the current number of child processes is less than the
 * maximum allowed (`MAX_PROCESSES`). If the maximum number of child processes
 * has been reached, an error message is printed to the standard error stream.
 *
 * @param pid The process ID of the child process to be added.
 */
void add_child_pid(pid_t pid);

/**
 * @brief Terminates all child processes and stops the monitor process if it is running.
 *
 * This function iterates through the list of child process IDs and sends a SIGKILL signal
 * to each one, effectively terminating them. After all child processes have been killed,
 * the number of child process IDs is reset to zero. If a monitor process is running, it
 * will also be stopped by calling the stop_monitor() function.
 */
void kill_all_child_processes();

/**
 * @brief Checks if a command exists in the system's PATH.
 *
 * This function checks if a given command is executable either by its direct path
 * or by searching through the directories listed in the system's PATH environment variable.
 *
 * @param command The name or path of the command to check.
 * @return 1 if the command exists and is executable, 0 otherwise.
 */
int command_exists(char* command);

/**
 * @brief Handles the specified signal.
 *
 * This function is called when a signal is received. If there is a process
 * running in the foreground, it sends the signal to that process. If the
 * signal is SIGTSTP (generated by pressing Ctrl+Z), it updates
 * the `suspended_pid` to the current `foreground_pid` and resets the
 * `foreground_pid` to -1, indicating no process is currently in the foreground.
 *
 * @param signal The signal number to handle.
 */
void handle_signal(int signal);

/**
 * @brief Changes the current working directory.
 *
 * This function changes the current working directory based on the arguments provided.
 * It supports changing to the home directory, the previous directory, or a specified directory.
 * It also updates the environment variables PWD and OLDPWD accordingly.
 *
 * @param args An array of arguments where args[0] is the command and args[1] is the directory to change to.
 *             If args[1] is NULL or "~", it changes to the home directory.
 *             If args[1] is "-", it changes to the previous directory.
 *             Otherwise, it changes to the directory specified by args[1].
 *
 * @note If the home directory cannot be determined, it uses the user's password entry to get the home directory.
 * @note If the previous directory (OLDPWD) is not set, it prints an error message.
 * @note If changing to the specified directory fails, it prints an error message.
 * @note If updating the current working directory (PWD) fails, it prints an error message and exits.
 */
void execute_cd(char* args[]);

/**
 * @brief Clears the terminal screen.
 *
 * This function sends the ANSI escape codes to clear the terminal screen
 * and move the cursor to the home position (top-left corner).
 */
void execute_clr();

/**
 * @brief Executes the echo command with optional output redirection and background execution.
 *
 * This function implements echo command. It can optionally redirect the output
 * to a specified file and run the command in the background.
 *
 * @param args An array of arguments where args[0] is the command name and subsequent elements are the arguments.
 *             If an argument starts with '$', it is treated as an environment variable and its value is printed.
 * @param output_file The path to the file where the output should be redirected. If NULL, output is printed to stdout.
 * @param background If non-zero, the command is executed in the background.
 *
 * The function handles the following:
 * - If background is non-zero, it forks a child process to execute the command.
 * - If output_file is not NULL, it redirects the output to the specified file.
 * - It prints the arguments, resolving environment variables if they start with '$'.
 * - In background mode, it adds the child process ID to a list and prints the job number and PID.
 * - In foreground mode, it restores the original stdout after execution.
 */
void execute_echo(char* args[], char* output_file, int background);

/**
 * @brief Terminates all child processes and exits the program.
 *
 * This function calls `kill_all_child_processes()` to terminate any child processes
 * that may be running, and then exits the program with a status code of 0.
 */
void execute_quit();

/**
 * @brief Resumes a suspended process and waits for it to change state.
 *
 * This function resumes a previously suspended process by sending it a SIGCONT signal.
 * It then waits for the process to change state (either to stop again or to terminate).
 * If the process stops again, it updates the suspended_pid variable.
 * If there is no suspended process, it prints a message indicating so.
 *
 * @note This function uses `suspended_pid` and `foreground_pid` as global variables.
 *
 * Global Variables:
 * - suspended_pid: The PID of the currently suspended process.
 * - foreground_pid: The PID of the process currently running in the foreground.
 * - num_child_pids: The number of child processes.
 *
 * Signals:
 * - SIGCONT: Signal sent to the suspended process to continue its execution.
 *
 * @return void
 */
void execute_fg();

/**
 * @brief Executes an external command with optional input/output redirection and background execution.
 *
 * This function forks a new process to execute the specified external command. It handles input and output
 * redirection if specified, and can run the command in the background if requested.
 *
 * @param args An array of argument strings for the command, with the first element being the command itself.
 * @param input_file A string representing the path to the input file for redirection, or NULL if not used.
 * @param output_file A string representing the path to the output file for redirection, or NULL if not used.
 * @param background An integer flag indicating whether to run the command in the background (non-zero) or foreground
 * (zero).
 *
 * @note This function assumes the existence of the following helper functions and variables:
 * - command_exists(const char *command): Checks if the command exists and is executable.
 * - add_child_pid(pid_t pid): Adds the given process ID to a list of child process IDs.
 * - num_child_pids: A global variable representing the number of child processes.
 * - foreground_pid: A global variable representing the process ID of the current foreground process.
 * - suspended_pid: A global variable representing the process ID of the suspended process.
 *
 * @return void
 */
void execute_external_command(char* args[], char* input_file, char* output_file, int background);

/**
 * @brief Executes a series of piped commands.
 *
 * This function takes an array of command strings and executes them in a pipeline.
 * Each command can have input and output redirection specified using '<' and '>' respectively.
 *
 * @param commands An array of command strings to be executed.
 * @param num_pipes The number of pipes to be created. This should be one less than the number of commands.
 *
 * The function creates the necessary pipes, forks child processes to execute each command,
 * and sets up the appropriate file descriptors for input and output redirection.
 * It waits for all child processes to complete before returning.
 *
 * Example usage:
 * @code
 * char *commands[] = {"ls -l", "grep .c", "wc -l"};
 * execute_piped_commands(commands, 2);
 * @endcode
 *
 * Error handling:
 * If any system call (pipe, fork, dup2, open, execvp) fails, the function prints an error message
 * and exits the program with a failure status.
 */
void execute_piped_commands(char* commands[], int num_pipes);

/**
 * @brief Starts the monitor process if it is not already running.
 *
 * This function checks if the monitor process is already running by examining
 * the global variable `monitor_pid`. If the monitor is not running, it forks
 * a new process. The child process executes the `metrics_executable` program
 * with the specified input and output file paths. If the fork or exec fails,
 * an error message is printed. If the monitor starts successfully, its PID is
 * printed along with the current configuration.
 *
 * @note The function assumes that `monitor_pid` is a global variable.
 * @note The function calls `show_config()` to display the current configuration.
 *
 * Error handling:
 * - If the monitor is already running, a message is printed and the function returns.
 * - If the fork fails, an error message is printed.
 * - If the exec fails, an error message is printed and the child process exits.
 */
void start_monitor();

/**
 * @brief Stops the monitoring program if it is running.
 *
 * This function checks if the monitoring program is running by verifying if
 * the global variable `monitor_pid` is greater than 0. If it is, the function
 * sends a SIGTERM signal to the process with the PID stored in `monitor_pid`,
 * waits for the process to terminate, and then prints a message indicating
 * that the monitoring program has been stopped. The `monitor_pid` is then set
 * to -1 to indicate that no monitoring program is currently running.
 * If no monitoring program is running, it prints a message indicating so.
 */
void stop_monitor();

/**
 * @brief Monitors the status of a program.
 *
 * This function checks the value of the global variable `monitor_pid` to determine
 * if a monitoring program is currently running. If `monitor_pid` is greater than 0,
 * it prints a message indicating that the monitoring program is running along with
 * its process ID (PID). If `monitor_pid` is 0 or less, it prints a message indicating
 * that no monitoring program is running.
 */
void status_monitor();

/**
 * @brief Reads the configuration from a JSON file specified by the environment variable CONFIG_FILE_PATH.
 *
 * This function reads the configuration file, parses the JSON content, and sets various global flags
 * based on the configuration. The configuration file should contain a "sampling_interval" field and
 * a "metrics" array specifying which metrics to enable.
 *
 * The following global variables are set based on the configuration:
 * - sleep_time: The sampling interval in seconds.
 * - cpu_enabled: Whether CPU metrics are enabled.
 * - memory_enabled: Whether memory metrics are enabled.
 * - battery_enabled: Whether battery metrics are enabled.
 * - avg_load_enabled: Whether average load metric is enabled.
 * - cpu_temp_enabled: Whether CPU temperature metric is enabled.
 * - cpu_speed_enabled: Whether CPU speed metric is enabled.
 * - processes_enabled: Whether process metrics are enabled.
 * - sys_calls_enabled: Whether system call metrics are enabled.
 * - disk_io_enabled: Whether disk I/O metrics are enabled.
 * - network_enabled: Whether network metrics are enabled.
 *
 * If the configuration file cannot be opened, read, or parsed, the function prints an error message
 * and exits the program.
 */
void read_config();

/**
 * @brief Updates the sampling interval in the configuration file.
 *
 * This function reads a JSON configuration file, updates the "sampling_interval"
 * field with the provided interval value, and writes the updated JSON back to the file.
 *
 * @param interval A string representing the new sampling interval value.
 *
 * 7. Frees allocated memory and closes the file.
 *
 * If any error occurs during these steps, the function prints an error message and exits the program.
 */
void update_interval(const char* interval);

/**
 * @brief Adds a metric to the JSON configuration file.
 *
 * This function reads a JSON configuration file specified by the environment variable
 * "CONFIG_FILE_PATH", adds a new metric to the "metrics" array in the JSON structure,
 * and writes the updated JSON back to the file.
 *
 * @param metric The metric to be added to the JSON configuration.
 *
 * If any error occurs during these steps, the function prints an error message and exits the program.
 */
void add_metric(const char* metric);

/**
 * @brief Removes a specified metric from the configuration file.
 *
 * This function reads a JSON configuration file, removes the specified metric
 * from the "metrics" array, and writes the updated configuration back to the file.
 *
 * @param metric The name of the metric to be removed.
 *
 * If any error occurs during these steps, the function prints an error message
 * and exits the program.
 */
void remove_metric(const char* metric);

/**
 * @brief Show the current configuration in JSON format.
 *
 * This function reads the current configuration using `read_config()`,
 * creates a JSON object, and populates it with the sampling interval
 * and enabled metrics. The JSON object is then printed to the standard
 * output.
 *
 * The metrics included in the JSON object are:
 * - "cpu" if `cpu_enabled` is true
 * - "memory" if `memory_enabled` is true
 * - "battery" if `battery_enabled` is true
 * - "avg_load" if `avg_load_enabled` is true
 * - "cpu_temp" if `cpu_temp_enabled` is true
 * - "cpu_speed" if `cpu_speed_enabled` is true
 * - "processes" if `processes_enabled` is true
 * - "sys_calls" if `sys_calls_enabled` is true
 * - "disk" if `disk_io_enabled` is true
 * - "network" if `network_enabled` is true
 *
 * The function performs cleanup by deleting the JSON object and freeing
 * the allocated memory for the JSON string.
 */
void show_config();
/**
 * @brief Maximum length of a command string.
 */
#define MAX_COMMAND_LENGTH 256
/**
 * @brief Maximum number of child processes.
 */
#define MAX_PROCESSES 100
/**
 * @brief User color for the shell prompt.
 * Light blue
 */
#define USER_COLOR "\033[1;36m"
/**
 * @brief PWD color for the shell prompt.
 * Pink
 */
#define PWD_COLOR "\033[1;35m"
/**
 * @brief Reset color for the shell prompt.
 * White
 */
#define BASE_COLOR "\033[0m"
/**
 * @brief Default file permissions for redirection.
 */
#define FILE_PERMISSIONS 0644
/**
 * @brief Constant to avoid magic numbers for background process.
 */
#define IS_BACKGROUND -1
/**
 * @brief Constant to avoid magic numbers for invalid process.
 */
#define INVALID_PID -1
/**
 * @brief Constant to avoid magic numbers for no foreground process.
 */
#define NO_FOREGROUND_PID -1
/**
 * @brief Constant to avoid magic numbers for no monitor process.
 */
#define NO_MONITOR_PID -1
/**
 * @brief Constant to avoid magic numbers for suspended process.
 */
#define SUSPENDED_PID 1
/**
 * @brief enum to avoid magic numbers for overwrite.
 */
extern enum
{
    NO_OVERWRITE = 0,
    OVERWRITE = 1
} overwrite;
/**
 * @brief Array to store child process IDs.
 */
extern pid_t child_pids[MAX_PROCESSES];
/**
 * @brief Process ID of the current foreground process.
 */
extern pid_t foreground_pid;
/**
 * @brief Process ID of the suspended process.
 */
extern pid_t suspended_pid1;
/**
 * @brief Number of child process IDs.
 */
extern int num_child_pids;
/**
 * @brief Job ID for background processes.
 */
extern int job_id;
/**
 * @brief Flag to enable/disable CPU metrics.
 */
extern bool cpu_enabled;
/**
 * @brief Flag to enable/disable memory metrics.
 */
extern bool memory_enabled;
/**
 * @brief Flag to enable/disable battery metrics.
 */
extern bool battery_enabled;
/**
 * @brief Flag to enable/disable average load metric.
 */
extern bool avg_load_enabled;
/**
 * @brief Flag to enable/disable CPU temperature metric.
 */
extern bool cpu_temp_enabled;
/**
 * @brief Flag to enable/disable CPU speed metric.
 */
extern bool cpu_speed_enabled;
/**
 * @brief Flag to enable/disable process metrics.
 */
extern bool processes_enabled;
/**
 * @brief Flag to enable/disable system call metrics.
 */
extern bool sys_calls_enabled;
/**
 * @brief Flag to enable/disable disk I/O metrics.
 */
extern bool disk_io_enabled;
/**
 * @brief Flag to enable/disable network metrics.
 */
extern bool network_enabled;
/**
 * @brief Sampling interval for monitoring.
 */
extern int sleep_time;
/**
 * @brief Process ID of the monitor process.
 */
extern pid_t monitor_pid1;


void explore_and_read_config_files(const char *directory, const char *extension);

#endif
